FROM python:3.12

# Installer les dépendances nécessaires dont cron pour execution périodique
RUN apt-get update && apt-get install -y cron

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier des dépendances
COPY ./requirements.txt /app/requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copier tout le code de l'application
COPY ./app/scrapping.py /app/scrapping.py
COPY ./app/crontab /etc/cron.d/scraping-cron

# Donner les permissions appropriées au fichier crontab
RUN chmod 0644 /etc/cron.d/scraping-cron

# Appliquer le crontab
RUN crontab /etc/cron.d/scraping-cron

# Démarrer le service cron
CMD ["cron", "-f"]