version: '3.9'

services:
  model-trainer-predictor:
    build:
      context: ./model-trainer-predictor
      dockerfile: Dockerfile
    volumes:
      - shared_raw:/app/data
      - shared_model:/app/model
      - mongodb_data:/app/mongo_db
    container_name: model_trainer_predictor

  scrapping_data:
    build:
      context: ./scrapping_data
      dockerfile: Dockerfile
    volumes:
      - shared_raw:/app/data
      - mongodb_data:/app/mongo_db
    container_name: scrapping_data

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - shared_raw:/data/raw
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongodb
    networks:
      - app

  mongodb_exporter:
  image: percona/mongodb_exporter
  environment:
    - MONGODB_URI=mongodb://antoine:pela@mongodb:27017/admin
  ports:
    - "9216:9216"  # Port par défaut pour l'exportateur
  networks:
    - app

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./fastapi/app:/app
      - shared_raw:/app/raw
      - shared_model:/app/model
      - shared_user_db:/app/user_db
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app
    container_name: fastapi

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
    networks:
      - app
    depends_on:
      - fastapi
    container_name: streamlit

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - shared_prometheus:/var/log/prometheus # Volume pour logs Prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - app

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    container_name: grafana
    networks:
      - app

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100" # Expose le port pour Node Exporter
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  shared_raw:
  shared_model:
  mongodb_data:
  shared_user_db:
  shared_prometheus:
  grafana_data: